#if EasyDOTween_UI

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.RectTransform
{
    using DG.Tweening;

    [UnityEngine.AddComponentMenu("EasyDOTween/RectTransform/DOSizeDelta"),
     UnityEngine.RequireComponent(typeof(UnityEngine.RectTransform))]
    public class DOSizeDelta : Animation<UnityEngine.RectTransform>
    {
        [UnityEngine.SerializeField()]
        private UnityEngine.Vector2 endValue;

        [UnityEngine.SerializeField()]
        private bool snapping = false;

        protected override Tween CreateTween(UnityEngine.RectTransform target, float duration) =>
            target.DOSizeDelta(endValue, duration, snapping);
    }
}

#endif
