#if EasyDOTween_UI

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.CanvasGroup
{
    using DG.Tweening;

    [UnityEngine.AddComponentMenu("EasyDOTween/CanvasGroup/DOFade"),
     UnityEngine.RequireComponent(typeof(UnityEngine.CanvasGroup))]
    public class DOFade : Animation<UnityEngine.CanvasGroup>
    {
        [UnityEngine.SerializeField()]
        private float endValue;

        protected override Tween CreateTween(UnityEngine.CanvasGroup target, float duration) =>
            target.DOFade(endValue, duration);
    }
}

#endif
