#if EasyDOTween_UI

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyDOTween.Animation.Graphic
{
    using DG.Tweening;

    [UnityEngine.AddComponentMenu("EasyDOTween/Graphic/DOColor"),
     UnityEngine.RequireComponent(typeof(UnityEngine.UI.Graphic))]
    public class DOColor : Animation<UnityEngine.UI.Graphic>
    {
        [UnityEngine.SerializeField()]
        private UnityEngine.Color endValue;

        protected override Tween CreateTween(UnityEngine.UI.Graphic target, float duration) =>
            target.DOColor(endValue, duration);
    }
}

#endif
